
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

discovery:
  ignore:
    - yeelight


fan:
  - platform: xiaomi_miio
    host: 192.168.18.131
    name: Air Purifier
    token: !secret air_purifier_token
    model: zhimi.airpurifier.m1

binary_sensor:
  - platform: ping
    host: 192.168.18.1
    count: 30
    name: Router
    scan_interval: 600

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
  radar:
    title: HKO Radar
    icon: mdi:blur-radial
    url: https://www.hko.gov.hk/en/wxinfo/radars/radar_range1.htm


shell_command:
  turn_ac_on:  "curl http://{{ ip }}/toshiba_ac/on" 
  turn_ac_off: "curl http://{{ ip }}/toshiba_ac/off"        

group: !include groups.yaml
automation: !include automations.yaml
#light: !include lights.yaml
input_boolean: !include input_booleans.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
yeelight: !include yeelights.yaml

python_script: 
