version: "3.8"
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /home/neo/nexus/pc/codecombat/mongodb:/data/db

  redis:
    image: "redis"

  codecombat:
    image: "codecombat"
    depends_on:
      - mongo  
      - redis
    
  # https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  nginx:
    image: "nginx"
    volumes:
      - /home/neo/nexus/pc/codecombat/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "8443:8443"
      - "8080:8080"
    # In the nginx section, you need to make sure that nginx reloads the newly obtained certificates:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mongo-express:
    image: "mongo-express"
    ports:
      - "8081:8081"    
    depends_on:
      - mongo  
    
      